# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manifest.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_name = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_name.setGeometry(QtCore.QRect(10, 20, 113, 21))
        self.txt_name.setObjectName("txt_name")
        self.lblName = QtWidgets.QLabel(self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(10, 0, 60, 16))
        self.lblName.setObjectName("lblName")
        self.txt_label = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_label.setGeometry(QtCore.QRect(10, 60, 113, 21))
        self.txt_label.setObjectName("txt_label")
        self.lblLabel = QtWidgets.QLabel(self.centralwidget)
        self.lblLabel.setGeometry(QtCore.QRect(10, 40, 60, 16))
        self.lblLabel.setObjectName("lblLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 0, 81, 16))
        self.label.setObjectName("label")
        self.txt_description = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_description.setGeometry(QtCore.QRect(160, 20, 221, 61))
        self.txt_description.setObjectName("txt_description")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 290, 60, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 370, 60, 16))
        self.label_10.setObjectName("label_10")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 100, 78, 174))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 100, 135, 171))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.txt_author = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_author.setObjectName("txt_author")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.txt_author)
        self.txt_maintainer = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_maintainer.setObjectName("txt_maintainer")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.txt_maintainer)
        self.txt_license = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_license.setObjectName("txt_license")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.txt_license)
        self.txt_url = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_url.setObjectName("txt_url")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.txt_url)
        self.txt_source = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_source.setObjectName("txt_source")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.txt_source)
        self.txt_cite = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_cite.setObjectName("txt_cite")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.txt_cite)
        self.txt_version = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_version.setObjectName("txt_version")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.txt_version)
        self.btn_make_manifest = QtWidgets.QPushButton(self.centralwidget)
        self.btn_make_manifest.setGeometry(QtCore.QRect(30, 460, 113, 32))
        self.btn_make_manifest.setObjectName("btn_make_manifest")
        self.cmbo_inputs = QtWidgets.QComboBox(self.centralwidget)
        self.cmbo_inputs.setGeometry(QtCore.QRect(70, 290, 171, 26))
        self.cmbo_inputs.setObjectName("cmbo_inputs")
        self.cmbo_inputs.addItem("")
        self.cmbo_inputs.addItem("")
        self.cmbo_config = QtWidgets.QComboBox(self.centralwidget)
        self.cmbo_config.setGeometry(QtCore.QRect(70, 370, 171, 26))
        self.cmbo_config.setObjectName("cmbo_config")
        self.rdo_utility = QtWidgets.QRadioButton(self.centralwidget)
        self.rdo_utility.setGeometry(QtCore.QRect(340, 240, 100, 20))
        self.rdo_utility.setObjectName("rdo_utility")
        self.rdo_analysis = QtWidgets.QRadioButton(self.centralwidget)
        self.rdo_analysis.setGeometry(QtCore.QRect(340, 260, 100, 20))
        self.rdo_analysis.setObjectName("rdo_analysis")
        self.chk_flywheel = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_flywheel.setGeometry(QtCore.QRect(340, 190, 111, 20))
        self.chk_flywheel.setObjectName("chk_flywheel")
        self.txt_suite = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_suite.setGeometry(QtCore.QRect(450, 190, 125, 21))
        self.txt_suite.setObjectName("txt_suite")
        self.btn_input_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_input_add.setGeometry(QtCore.QRect(70, 310, 51, 32))
        self.btn_input_add.setObjectName("btn_input_add")
        self.btn_input_edit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_input_edit.setGeometry(QtCore.QRect(120, 310, 51, 32))
        self.btn_input_edit.setObjectName("btn_input_edit")
        self.btn_input_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_input_delete.setGeometry(QtCore.QRect(170, 310, 61, 32))
        self.btn_input_delete.setObjectName("btn_input_delete")
        self.btn_config_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_config_delete.setGeometry(QtCore.QRect(170, 390, 61, 32))
        self.btn_config_delete.setObjectName("btn_config_delete")
        self.btn_config_edit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_config_edit.setGeometry(QtCore.QRect(120, 390, 51, 32))
        self.btn_config_edit.setObjectName("btn_config_edit")
        self.btn_config_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_config_add.setGeometry(QtCore.QRect(70, 390, 51, 32))
        self.btn_config_add.setObjectName("btn_config_add")
        self.btn_make_manifest_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_make_manifest_2.setGeometry(QtCore.QRect(140, 460, 113, 32))
        self.btn_make_manifest_2.setObjectName("btn_make_manifest_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_name.setText(_translate("MainWindow", "test-gear"))
        self.lblName.setText(_translate("MainWindow", "name:"))
        self.txt_label.setText(_translate("MainWindow", "Test Gear"))
        self.lblLabel.setText(_translate("MainWindow", "label:"))
        self.label.setText(_translate("MainWindow", "Description:"))
        self.txt_description.setPlainText(_translate("MainWindow", "This is a Test Gear. Use with caution."))
        self.label_9.setText(_translate("MainWindow", "inputs:"))
        self.label_10.setText(_translate("MainWindow", "config:"))
        self.label_2.setText(_translate("MainWindow", "Author:"))
        self.label_3.setText(_translate("MainWindow", "maintainer:"))
        self.label_4.setText(_translate("MainWindow", "License:"))
        self.label_5.setText(_translate("MainWindow", "url:"))
        self.label_6.setText(_translate("MainWindow", "source:"))
        self.label_7.setText(_translate("MainWindow", "cite:"))
        self.label_8.setText(_translate("MainWindow", "version:"))
        self.txt_author.setText(_translate("MainWindow", "Flywheel"))
        self.txt_maintainer.setText(_translate("MainWindow", "Flywheel <support@flywheel.io>"))
        self.txt_license.setText(_translate("MainWindow", "Other"))
        self.txt_url.setText(_translate("MainWindow", "https://github.com/flywheel-apps/test-gear"))
        self.txt_version.setText(_translate("MainWindow", "0.0.1"))
        self.btn_make_manifest.setText(_translate("MainWindow", "save manifest"))
        self.cmbo_inputs.setItemText(0, _translate("MainWindow", "Item 1"))
        self.cmbo_inputs.setItemText(1, _translate("MainWindow", "Item 2"))
        self.rdo_utility.setText(_translate("MainWindow", "Utility"))
        self.rdo_analysis.setText(_translate("MainWindow", "Analysis"))
        self.chk_flywheel.setText(_translate("MainWindow", "flywheel suite"))
        self.txt_suite.setText(_translate("MainWindow", "One Suite World"))
        self.btn_input_add.setText(_translate("MainWindow", "Add"))
        self.btn_input_edit.setText(_translate("MainWindow", "Edit"))
        self.btn_input_delete.setText(_translate("MainWindow", "Delete"))
        self.btn_config_delete.setText(_translate("MainWindow", "Delete"))
        self.btn_config_edit.setText(_translate("MainWindow", "Edit"))
        self.btn_config_add.setText(_translate("MainWindow", "Add"))
        self.btn_make_manifest_2.setText(_translate("MainWindow", "load manifest"))

