# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gear_builder_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(635, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 621, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tb_manifest = QtWidgets.QWidget()
        self.tb_manifest.setObjectName("tb_manifest")
        self.btn_input_delete = QtWidgets.QPushButton(self.tb_manifest)
        self.btn_input_delete.setGeometry(QtCore.QRect(210, 390, 61, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_delete.sizePolicy().hasHeightForWidth())
        self.btn_input_delete.setSizePolicy(sizePolicy)
        self.btn_input_delete.setObjectName("btn_input_delete")
        self.label_9 = QtWidgets.QLabel(self.tb_manifest)
        self.label_9.setGeometry(QtCore.QRect(32, 364, 60, 16))
        self.label_9.setObjectName("label_9")
        self.btn_config_edit = QtWidgets.QPushButton(self.tb_manifest)
        self.btn_config_edit.setGeometry(QtCore.QRect(150, 450, 51, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_config_edit.sizePolicy().hasHeightForWidth())
        self.btn_config_edit.setSizePolicy(sizePolicy)
        self.btn_config_edit.setObjectName("btn_config_edit")
        self.txt_label = QtWidgets.QLineEdit(self.tb_manifest)
        self.txt_label.setGeometry(QtCore.QRect(70, 90, 131, 20))
        self.txt_label.setMaxLength(100)
        self.txt_label.setObjectName("txt_label")
        self.txt_name = QtWidgets.QLineEdit(self.tb_manifest)
        self.txt_name.setGeometry(QtCore.QRect(70, 50, 131, 20))
        self.txt_name.setMaxLength(100)
        self.txt_name.setObjectName("txt_name")
        self.label = QtWidgets.QLabel(self.tb_manifest)
        self.label.setGeometry(QtCore.QRect(220, 30, 131, 16))
        self.label.setObjectName("label")
        self.lblName = QtWidgets.QLabel(self.tb_manifest)
        self.lblName.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.lblName.setObjectName("lblName")
        self.rdo_analysis = QtWidgets.QRadioButton(self.tb_manifest)
        self.rdo_analysis.setGeometry(QtCore.QRect(460, 210, 100, 20))
        self.rdo_analysis.setChecked(True)
        self.rdo_analysis.setObjectName("rdo_analysis")
        self.txt_description = QtWidgets.QPlainTextEdit(self.tb_manifest)
        self.txt_description.setGeometry(QtCore.QRect(220, 50, 361, 61))
        self.txt_description.setObjectName("txt_description")
        self.txt_suite = QtWidgets.QLineEdit(self.tb_manifest)
        self.txt_suite.setGeometry(QtCore.QRect(460, 160, 151, 21))
        self.txt_suite.setMaxLength(100)
        self.txt_suite.setObjectName("txt_suite")
        self.layoutWidget = QtWidgets.QWidget(self.tb_manifest)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 120, 411, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.txt_author = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_author.sizePolicy().hasHeightForWidth())
        self.txt_author.setSizePolicy(sizePolicy)
        self.txt_author.setMaxLength(100)
        self.txt_author.setObjectName("txt_author")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_author)
        self.txt_maintainer = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_maintainer.sizePolicy().hasHeightForWidth())
        self.txt_maintainer.setSizePolicy(sizePolicy)
        self.txt_maintainer.setMaxLength(100)
        self.txt_maintainer.setCursorPosition(0)
        self.txt_maintainer.setObjectName("txt_maintainer")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_maintainer)
        self.txt_license = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_license.sizePolicy().hasHeightForWidth())
        self.txt_license.setSizePolicy(sizePolicy)
        self.txt_license.setCurrentText("")
        self.txt_license.setObjectName("txt_license")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_license)
        self.txt_url = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_url.sizePolicy().hasHeightForWidth())
        self.txt_url.setSizePolicy(sizePolicy)
        self.txt_url.setCursorPosition(0)
        self.txt_url.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_url.setObjectName("txt_url")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_url)
        self.txt_cite = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_cite.sizePolicy().hasHeightForWidth())
        self.txt_cite.setSizePolicy(sizePolicy)
        self.txt_cite.setMaxLength(5000)
        self.txt_cite.setObjectName("txt_cite")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_cite)
        self.txt_version = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_version.sizePolicy().hasHeightForWidth())
        self.txt_version.setSizePolicy(sizePolicy)
        self.txt_version.setMinimumSize(QtCore.QSize(0, 18))
        self.txt_version.setMaxLength(100)
        self.txt_version.setObjectName("txt_version")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_version)
        self.txt_source = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_source.sizePolicy().hasHeightForWidth())
        self.txt_source.setSizePolicy(sizePolicy)
        self.txt_source.setWhatsThis("")
        self.txt_source.setText("")
        self.txt_source.setObjectName("txt_source")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_source)
        self.btn_config_add = QtWidgets.QPushButton(self.tb_manifest)
        self.btn_config_add.setGeometry(QtCore.QRect(92, 450, 51, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_config_add.sizePolicy().hasHeightForWidth())
        self.btn_config_add.setSizePolicy(sizePolicy)
        self.btn_config_add.setObjectName("btn_config_add")
        self.btn_config_delete = QtWidgets.QPushButton(self.tb_manifest)
        self.btn_config_delete.setGeometry(QtCore.QRect(210, 450, 61, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_config_delete.sizePolicy().hasHeightForWidth())
        self.btn_config_delete.setSizePolicy(sizePolicy)
        self.btn_config_delete.setObjectName("btn_config_delete")
        self.btn_input_add = QtWidgets.QPushButton(self.tb_manifest)
        self.btn_input_add.setGeometry(QtCore.QRect(90, 390, 51, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_add.sizePolicy().hasHeightForWidth())
        self.btn_input_add.setSizePolicy(sizePolicy)
        self.btn_input_add.setObjectName("btn_input_add")
        self.rdo_utility = QtWidgets.QRadioButton(self.tb_manifest)
        self.rdo_utility.setGeometry(QtCore.QRect(460, 190, 100, 20))
        self.rdo_utility.setObjectName("rdo_utility")
        self.btn_load_manifest = QtWidgets.QPushButton(self.tb_manifest)
        self.btn_load_manifest.setGeometry(QtCore.QRect(230, 480, 131, 32))
        self.btn_load_manifest.setObjectName("btn_load_manifest")
        self.btn_input_edit = QtWidgets.QPushButton(self.tb_manifest)
        self.btn_input_edit.setGeometry(QtCore.QRect(150, 390, 51, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input_edit.sizePolicy().hasHeightForWidth())
        self.btn_input_edit.setSizePolicy(sizePolicy)
        self.btn_input_edit.setObjectName("btn_input_edit")
        self.cmbo_inputs = QtWidgets.QComboBox(self.tb_manifest)
        self.cmbo_inputs.setGeometry(QtCore.QRect(90, 360, 181, 26))
        self.cmbo_inputs.setObjectName("cmbo_inputs")
        self.chk_flywheel = QtWidgets.QCheckBox(self.tb_manifest)
        self.chk_flywheel.setGeometry(QtCore.QRect(460, 130, 141, 20))
        self.chk_flywheel.setObjectName("chk_flywheel")
        self.btn_save_manifest = QtWidgets.QPushButton(self.tb_manifest)
        self.btn_save_manifest.setGeometry(QtCore.QRect(90, 480, 131, 32))
        self.btn_save_manifest.setObjectName("btn_save_manifest")
        self.cmbo_config = QtWidgets.QComboBox(self.tb_manifest)
        self.cmbo_config.setGeometry(QtCore.QRect(92, 420, 181, 26))
        self.cmbo_config.setObjectName("cmbo_config")
        self.lblLabel = QtWidgets.QLabel(self.tb_manifest)
        self.lblLabel.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.lblLabel.setObjectName("lblLabel")
        self.label_10 = QtWidgets.QLabel(self.tb_manifest)
        self.label_10.setGeometry(QtCore.QRect(30, 414, 60, 41))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tb_manifest, "")
        self.tb_dockerfile = QtWidgets.QWidget()
        self.tb_dockerfile.setObjectName("tb_dockerfile")
        self.label_11 = QtWidgets.QLabel(self.tb_dockerfile)
        self.label_11.setGeometry(QtCore.QRect(150, 10, 141, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tb_dockerfile)
        self.label_12.setGeometry(QtCore.QRect(150, 120, 201, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tb_dockerfile)
        self.label_13.setGeometry(QtCore.QRect(150, 240, 201, 16))
        self.label_13.setObjectName("label_13")
        self.txt_maintainer_2 = QtWidgets.QLineEdit(self.tb_dockerfile)
        self.txt_maintainer_2.setGeometry(QtCore.QRect(280, 80, 211, 21))
        self.txt_maintainer_2.setObjectName("txt_maintainer_2")
        self.label_15 = QtWidgets.QLabel(self.tb_dockerfile)
        self.label_15.setGeometry(QtCore.QRect(190, 80, 81, 16))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.tb_dockerfile)
        self.label_17.setGeometry(QtCore.QRect(150, 370, 201, 16))
        self.label_17.setObjectName("label_17")
        self.tblENV = QtWidgets.QTableWidget(self.tb_dockerfile)
        self.tblENV.setGeometry(QtCore.QRect(150, 390, 331, 91))
        self.tblENV.setRowCount(2)
        self.tblENV.setObjectName("tblENV")
        self.tblENV.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tblENV.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblENV.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblENV.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblENV.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblENV.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblENV.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblENV.setItem(1, 1, item)
        self.tblENV.horizontalHeader().setDefaultSectionSize(150)
        self.tblENV.horizontalHeader().setSortIndicatorShown(False)
        self.tblENV.horizontalHeader().setStretchLastSection(True)
        self.tblENV.verticalHeader().setSortIndicatorShown(False)
        self.tblENV.verticalHeader().setStretchLastSection(False)
        self.btn_ENV_del = QtWidgets.QPushButton(self.tb_dockerfile)
        self.btn_ENV_del.setGeometry(QtCore.QRect(480, 420, 51, 32))
        self.btn_ENV_del.setObjectName("btn_ENV_del")
        self.btn_ENV_add = QtWidgets.QPushButton(self.tb_dockerfile)
        self.btn_ENV_add.setGeometry(QtCore.QRect(480, 390, 51, 32))
        self.btn_ENV_add.setObjectName("btn_ENV_add")
        self.btn_PIP_del = QtWidgets.QPushButton(self.tb_dockerfile)
        self.btn_PIP_del.setGeometry(QtCore.QRect(480, 290, 51, 32))
        self.btn_PIP_del.setObjectName("btn_PIP_del")
        self.btn_PIP_add = QtWidgets.QPushButton(self.tb_dockerfile)
        self.btn_PIP_add.setGeometry(QtCore.QRect(480, 260, 51, 32))
        self.btn_PIP_add.setObjectName("btn_PIP_add")
        self.tblPIP = QtWidgets.QTableWidget(self.tb_dockerfile)
        self.tblPIP.setGeometry(QtCore.QRect(150, 260, 331, 91))
        self.tblPIP.setRowCount(2)
        self.tblPIP.setObjectName("tblPIP")
        self.tblPIP.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tblPIP.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPIP.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPIP.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPIP.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPIP.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPIP.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPIP.setItem(1, 1, item)
        self.tblPIP.horizontalHeader().setDefaultSectionSize(150)
        self.tblPIP.horizontalHeader().setSortIndicatorShown(False)
        self.tblPIP.horizontalHeader().setStretchLastSection(True)
        self.tblPIP.verticalHeader().setSortIndicatorShown(False)
        self.tblPIP.verticalHeader().setStretchLastSection(False)
        self.tblAPT = QtWidgets.QTableWidget(self.tb_dockerfile)
        self.tblAPT.setGeometry(QtCore.QRect(150, 140, 331, 91))
        self.tblAPT.setRowCount(2)
        self.tblAPT.setObjectName("tblAPT")
        self.tblAPT.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tblAPT.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAPT.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAPT.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAPT.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAPT.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAPT.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAPT.setItem(1, 1, item)
        self.tblAPT.horizontalHeader().setDefaultSectionSize(150)
        self.tblAPT.horizontalHeader().setSortIndicatorShown(False)
        self.tblAPT.horizontalHeader().setStretchLastSection(True)
        self.tblAPT.verticalHeader().setSortIndicatorShown(False)
        self.tblAPT.verticalHeader().setStretchLastSection(False)
        self.btn_APT_del = QtWidgets.QPushButton(self.tb_dockerfile)
        self.btn_APT_del.setGeometry(QtCore.QRect(480, 170, 51, 32))
        self.btn_APT_del.setObjectName("btn_APT_del")
        self.btn_APT_add = QtWidgets.QPushButton(self.tb_dockerfile)
        self.btn_APT_add.setGeometry(QtCore.QRect(480, 140, 51, 32))
        self.btn_APT_add.setObjectName("btn_APT_add")
        self.cbo_docker_source = QtWidgets.QComboBox(self.tb_dockerfile)
        self.cbo_docker_source.setGeometry(QtCore.QRect(280, 10, 161, 30))
        self.cbo_docker_source.setEditable(True)
        self.cbo_docker_source.setObjectName("cbo_docker_source")
        self.cbo_docker_source.addItem("")
        self.cbo_docker_source.addItem("")
        self.cbo_docker_source.addItem("")
        self.tabWidget.addTab(self.tb_dockerfile, "")
        self.tb_scripts = QtWidgets.QWidget()
        self.tb_scripts.setObjectName("tb_scripts")
        self.label_14 = QtWidgets.QLabel(self.tb_scripts)
        self.label_14.setGeometry(QtCore.QRect(80, 290, 451, 181))
        self.label_14.setObjectName("label_14")
        self.cbo_script_template = QtWidgets.QComboBox(self.tb_scripts)
        self.cbo_script_template.setGeometry(QtCore.QRect(10, 20, 170, 26))
        self.cbo_script_template.setObjectName("cbo_script_template")
        self.label_18 = QtWidgets.QLabel(self.tb_scripts)
        self.label_18.setGeometry(QtCore.QRect(10, 0, 131, 16))
        self.label_18.setObjectName("label_18")
        self.scrOptions = QtWidgets.QScrollArea(self.tb_scripts)
        self.scrOptions.setGeometry(QtCore.QRect(10, 110, 501, 111))
        self.scrOptions.setWidgetResizable(True)
        self.scrOptions.setObjectName("scrOptions")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 109))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrOptions.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tb_scripts, "")
        self.btn_export_gear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export_gear.setGeometry(QtCore.QRect(10, 590, 101, 32))
        self.btn_export_gear.setObjectName("btn_export_gear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 635, 22))
        self.menubar.setObjectName("menubar")
        self.menuhello = QtWidgets.QMenu(self.menubar)
        self.menuhello.setObjectName("menuhello")
        self.menuDocker = QtWidgets.QMenu(self.menubar)
        self.menuDocker.setObjectName("menuDocker")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Gear_Project = QtWidgets.QAction(MainWindow)
        self.actionLoad_Gear_Project.setObjectName("actionLoad_Gear_Project")
        self.actionSave_Gear_Project = QtWidgets.QAction(MainWindow)
        self.actionSave_Gear_Project.setObjectName("actionSave_Gear_Project")
        self.actionBuild_Docker = QtWidgets.QAction(MainWindow)
        self.actionBuild_Docker.setObjectName("actionBuild_Docker")
        self.actionRun_Docker = QtWidgets.QAction(MainWindow)
        self.actionRun_Docker.setObjectName("actionRun_Docker")
        self.actionExport_Gear = QtWidgets.QAction(MainWindow)
        self.actionExport_Gear.setObjectName("actionExport_Gear")
        self.actionUpload_Gear = QtWidgets.QAction(MainWindow)
        self.actionUpload_Gear.setObjectName("actionUpload_Gear")
        self.menuhello.addAction(self.actionLoad_Gear_Project)
        self.menuhello.addAction(self.actionSave_Gear_Project)
        self.menuhello.addAction(self.actionExport_Gear)
        self.menuhello.addAction(self.actionUpload_Gear)
        self.menuDocker.addAction(self.actionBuild_Docker)
        self.menuDocker.addAction(self.actionRun_Docker)
        self.menubar.addAction(self.menuhello.menuAction())
        self.menubar.addAction(self.menuDocker.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_name, self.txt_label)
        MainWindow.setTabOrder(self.txt_label, self.txt_description)
        MainWindow.setTabOrder(self.txt_description, self.chk_flywheel)
        MainWindow.setTabOrder(self.chk_flywheel, self.txt_suite)
        MainWindow.setTabOrder(self.txt_suite, self.rdo_utility)
        MainWindow.setTabOrder(self.rdo_utility, self.rdo_analysis)
        MainWindow.setTabOrder(self.rdo_analysis, self.cmbo_inputs)
        MainWindow.setTabOrder(self.cmbo_inputs, self.btn_input_add)
        MainWindow.setTabOrder(self.btn_input_add, self.btn_input_edit)
        MainWindow.setTabOrder(self.btn_input_edit, self.btn_input_delete)
        MainWindow.setTabOrder(self.btn_input_delete, self.cmbo_config)
        MainWindow.setTabOrder(self.cmbo_config, self.btn_config_add)
        MainWindow.setTabOrder(self.btn_config_add, self.btn_config_edit)
        MainWindow.setTabOrder(self.btn_config_edit, self.btn_config_delete)
        MainWindow.setTabOrder(self.btn_config_delete, self.btn_save_manifest)
        MainWindow.setTabOrder(self.btn_save_manifest, self.btn_load_manifest)
        MainWindow.setTabOrder(self.btn_load_manifest, self.cbo_docker_source)
        MainWindow.setTabOrder(self.cbo_docker_source, self.txt_maintainer_2)
        MainWindow.setTabOrder(self.txt_maintainer_2, self.tblAPT)
        MainWindow.setTabOrder(self.tblAPT, self.btn_APT_add)
        MainWindow.setTabOrder(self.btn_APT_add, self.btn_APT_del)
        MainWindow.setTabOrder(self.btn_APT_del, self.tblPIP)
        MainWindow.setTabOrder(self.tblPIP, self.btn_PIP_add)
        MainWindow.setTabOrder(self.btn_PIP_add, self.btn_PIP_del)
        MainWindow.setTabOrder(self.btn_PIP_del, self.tblENV)
        MainWindow.setTabOrder(self.tblENV, self.btn_ENV_add)
        MainWindow.setTabOrder(self.btn_ENV_add, self.btn_ENV_del)
        MainWindow.setTabOrder(self.btn_ENV_del, self.cbo_script_template)
        MainWindow.setTabOrder(self.cbo_script_template, self.btn_export_gear)
        MainWindow.setTabOrder(self.btn_export_gear, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gear Builder"))
        self.btn_input_delete.setText(_translate("MainWindow", "Delete"))
        self.label_9.setText(_translate("MainWindow", "inputs:"))
        self.btn_config_edit.setText(_translate("MainWindow", "Edit"))
        self.txt_label.setText(_translate("MainWindow", "Test Gear"))
        self.txt_name.setText(_translate("MainWindow", "test-gear"))
        self.label.setText(_translate("MainWindow", "Description:"))
        self.lblName.setText(_translate("MainWindow", "name:"))
        self.rdo_analysis.setText(_translate("MainWindow", "Analysis"))
        self.txt_description.setPlainText(_translate("MainWindow", "This is a Test Gear. Use with caution."))
        self.txt_suite.setText(_translate("MainWindow", "One Suite World"))
        self.label_2.setText(_translate("MainWindow", "Author:"))
        self.label_3.setText(_translate("MainWindow", "maintainer:"))
        self.label_4.setText(_translate("MainWindow", "License:"))
        self.label_5.setText(_translate("MainWindow", "url:"))
        self.label_6.setText(_translate("MainWindow", "source:"))
        self.label_7.setText(_translate("MainWindow", "cite:"))
        self.label_8.setText(_translate("MainWindow", "version:"))
        self.txt_author.setText(_translate("MainWindow", "Flywheel"))
        self.txt_maintainer.setText(_translate("MainWindow", "Flywheel <support@flywheel.io>"))
        self.txt_url.setText(_translate("MainWindow", "https://github.com/flywheel-apps/test-gear"))
        self.txt_version.setText(_translate("MainWindow", "0.0.1"))
        self.btn_config_add.setText(_translate("MainWindow", "Add"))
        self.btn_config_delete.setText(_translate("MainWindow", "Delete"))
        self.btn_input_add.setText(_translate("MainWindow", "Add"))
        self.rdo_utility.setText(_translate("MainWindow", "Utility"))
        self.btn_load_manifest.setText(_translate("MainWindow", "load manifest"))
        self.btn_input_edit.setText(_translate("MainWindow", "Edit"))
        self.cmbo_inputs.setToolTip(_translate("MainWindow", "Yo Muther Fucker"))
        self.chk_flywheel.setText(_translate("MainWindow", "flywheel suite"))
        self.btn_save_manifest.setText(_translate("MainWindow", "save manifest"))
        self.lblLabel.setText(_translate("MainWindow", "label:"))
        self.label_10.setText(_translate("MainWindow", "config:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_manifest), _translate("MainWindow", "Manifest"))
        self.label_11.setText(_translate("MainWindow", "Select Source Image:"))
        self.label_12.setText(_translate("MainWindow", "Indicate apt-get dependencies:"))
        self.label_13.setText(_translate("MainWindow", "Indicate python dependencies:"))
        self.txt_maintainer_2.setText(_translate("MainWindow", "Flywheel <support@flywheel.io>"))
        self.label_15.setText(_translate("MainWindow", "maintainer:"))
        self.label_17.setText(_translate("MainWindow", "Set ENV variables:"))
        item = self.tblENV.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tblENV.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Variable"))
        item = self.tblENV.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.tblENV.isSortingEnabled()
        self.tblENV.setSortingEnabled(False)
        item = self.tblENV.item(0, 0)
        item.setText(_translate("MainWindow", "PATH"))
        item = self.tblENV.item(0, 1)
        item.setText(_translate("MainWindow", "$PATH"))
        item = self.tblENV.item(1, 0)
        item.setText(_translate("MainWindow", "LD_LIBRARY_PATH"))
        item = self.tblENV.item(1, 1)
        item.setText(_translate("MainWindow", "$LD_LIBRARY_PATH"))
        self.tblENV.setSortingEnabled(__sortingEnabled)
        self.btn_ENV_del.setText(_translate("MainWindow", "Del"))
        self.btn_ENV_add.setText(_translate("MainWindow", "Add"))
        self.btn_PIP_del.setText(_translate("MainWindow", "Del"))
        self.btn_PIP_add.setText(_translate("MainWindow", "Add"))
        item = self.tblPIP.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tblPIP.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Package"))
        item = self.tblPIP.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Version (Required)"))
        __sortingEnabled = self.tblPIP.isSortingEnabled()
        self.tblPIP.setSortingEnabled(False)
        item = self.tblPIP.item(0, 0)
        item.setText(_translate("MainWindow", "flywheel-sdk"))
        item = self.tblPIP.item(1, 0)
        item.setText(_translate("MainWindow", "nibabel"))
        self.tblPIP.setSortingEnabled(__sortingEnabled)
        item = self.tblAPT.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tblAPT.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Package"))
        item = self.tblAPT.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Version (Optional)"))
        __sortingEnabled = self.tblAPT.isSortingEnabled()
        self.tblAPT.setSortingEnabled(False)
        item = self.tblAPT.item(0, 0)
        item.setText(_translate("MainWindow", "python3-pip"))
        item = self.tblAPT.item(1, 0)
        item.setText(_translate("MainWindow", "zip"))
        self.tblAPT.setSortingEnabled(__sortingEnabled)
        self.btn_APT_del.setText(_translate("MainWindow", "Del"))
        self.btn_APT_add.setText(_translate("MainWindow", "Add"))
        self.cbo_docker_source.setItemText(0, _translate("MainWindow", "ubuntu:xenial"))
        self.cbo_docker_source.setItemText(1, _translate("MainWindow", "vistalab/fsl-v5.0"))
        self.cbo_docker_source.setItemText(2, _translate("MainWindow", "python:3.7.7-stretch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_dockerfile), _translate("MainWindow", "Dockerfile"))
        self.label_14.setText(_translate("MainWindow", "Provide the base run.py and utils package.\n"
"Creating build/validate/execute functional modules around specific command-line programs.\n"
"Add a command-line \"switch-detector\" to populate the manifest config with values to loop through.\n"
"Provide a library of code-blocks that facilitate certain functionality\n"
"module-based log reporting\n"
"bids functionality\n"
"verbose config validation against manifest\n"
"compress working directory to a file in output\n"
"notify on pep8 violations(??)"))
        self.label_18.setText(_translate("MainWindow", "Script Template:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_scripts), _translate("MainWindow", "Script Management"))
        self.btn_export_gear.setText(_translate("MainWindow", "Export Gear"))
        self.menuhello.setTitle(_translate("MainWindow", "Gear"))
        self.menuDocker.setTitle(_translate("MainWindow", "Docker"))
        self.actionLoad_Gear_Project.setText(_translate("MainWindow", "Load Gear Project"))
        self.actionSave_Gear_Project.setText(_translate("MainWindow", "Save Gear Project"))
        self.actionBuild_Docker.setText(_translate("MainWindow", "Build Docker"))
        self.actionRun_Docker.setText(_translate("MainWindow", "Run Docker"))
        self.actionExport_Gear.setText(_translate("MainWindow", "Export Gear"))
        self.actionUpload_Gear.setText(_translate("MainWindow", "Upload Gear"))
